### ISSUE TITLE
[Bug] bot.send(str) 无法自动转义特殊字符

### ISSUE THREAD

**Issue by EnderHane** [nonebot/adapter-satori#12]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个Bug

# Bug

## 问题
send 传入 str 时[特殊字符](https://satori.chat/zh-CN/protocol/message.html#%E5%AD%97%E7%AC%A6)未被转义
（使用MessageSegment.text(str)包装后可以自动转义）

## 如何复现
```
help_msg = 'command usage: /some_cmd <required_arg> [optional_arg]'
await matcher.finish(help_msg)
```
收到的是
> command usage: /some_cmd &nbsp;[optional_arg]

## 使用环境:
- 操作系统 (Windows/Linux/Mac):
- Python 版本: 3.12.1
- Nonebot2 版本: 2.1.3
- 适配器版本: 0.8.3
- 使用的 Satori 服务端 (例如 Chronocat):

**Comment by RF-Tar-Railt** [comment]
我想的是bot.send(str)就直接发送raw content了（手搓 satori 消息）
