### ISSUE TITLE
[Bug]: 请问是没有主动群消息发送的接口吗

### ISSUE THREAD

**Issue by Pasumao** [nonebot/adapter-satori#15]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个 Bug
- [X] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.11

### NoneBot 版本

2.0.0

### 适配器

0.1

### 协议端

cc

### 描述问题

如题
好像是[Satori]本身把channel_create这个给禁止了，所以是不是没办法主动发送群消息

### 复现步骤

如题

**Comment by RF-Tar-Railt** [comment]
？channel_create是创建新的群聊，你发生主动群消息应该是用bot.send_message(channel_id="xxxx", message=...)

**Comment by RF-Tar-Railt** [comment]
bot怎么拿文档应该写了
