### ISSUE TITLE
[Bug]: Satori Adapter不支持使用Nonebot Alconna解析命令

### ISSUE THREAD

**Issue by LiXDL** [nonebot/adapter-satori#16]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个 Bug
- [ ] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.12.2

### NoneBot 版本

2.2.1

### 适配器

0.10.1

### 协议端

Chronocat

### 描述问题

使用on_alconna构造的事件响应器报错并提示`Message Exporter not found under adapter Satori`

### 复现步骤

1. 使用QQNT和LiteLoader启用Choronocat
2. bot正常连接并加载插件
3. 触发使用on_alconna构造的事件响应器即会报错

### 截图或日志

1.事件响应器定义：
![image](https://github.com/nonebot/adapter-satori/assets/38141753/4520112c-b0d1-47cc-9cfd-bdde38853737)
2.处理函数定义：
![image](https://github.com/nonebot/adapter-satori/assets/38141753/6858534d-c26c-41fa-9110-73fe037fd91b)
3.Traceback：
<img width="1052" alt="image" src="https://github.com/nonebot/adapter-satori/assets/38141753/39a30a5f-3427-4626-8382-2ada46aaf710">

**Comment by RF-Tar-Railt** [comment]
bot启动的时候有什么RuntimeWarning吗

**Comment by RF-Tar-Railt** [comment]
？

**Comment by RF-Tar-Railt** [comment]
在吗？

**Comment by LiXDL** [comment]
大哥，我昨天发完issue就睡了，白天上班没条件测，晚上测完给你反馈🧎🏻‍♂️

**Comment by LiXDL** [comment]
<img width="1517" alt="image" src="https://github.com/nonebot/adapter-satori/assets/38141753/e4075b95-e769-4e3d-a8e6-1e11b14bab85">
启动的时候都正常的

**Comment by RF-Tar-Railt** [comment]
你用的什么版本的alc

**Comment by LiXDL** [comment]
nb的alconna插件是0.42.4，arclet-alconna是1.8.9

**Comment by RF-Tar-Railt** [comment]
怪了，我这边没有碰到这个问题
![image](https://github.com/nonebot/adapter-satori/assets/42648639/b1f50047-9562-4554-abb4-7ab15a9699bc)
![image](https://github.com/nonebot/adapter-satori/assets/42648639/f6644e76-f5ef-4013-8da0-50c38aeb6cd2)

**Comment by LiXDL** [comment]
刚刚更新了一下satori adapter到0.10.4，没有报错，但是前面我写的那个事件响应器也没有被命令触发。
我看alconna那边好像也是您在维护，顺带问问，on_alconna构造出来的响应器是不是不会注入bot和event这类nb自己的依赖。

**Comment by RF-Tar-Railt** [comment]
> 刚刚更新了一下satori adapter到0.10.4，没有报错，但是前面我写的那个事件响应器也没有被命令触发。 我看alconna那边好像也是您在维护，顺带问问，on_alconna构造出来的响应器是不是不会注入bot和event这类nb自己的依赖。

1. 你看看是不是 permission设置错了，或者你没有带command_start
2. bot和event会注入的

**Comment by LiXDL** [comment]
感谢感谢，解决了！
