### ISSUE TITLE
[Bug]: 接收到带有at机器人的命令无法通过nonebot.rule自带的to_me()响应规则检查

### ISSUE THREAD

**Issue by LiXDL** [nonebot/adapter-satori#17]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个 Bug
- [ ] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.12.2

### NoneBot 版本

2.2.1

### 适配器

0.10.5

### 协议端

Chronocat

### 描述问题

使用`on_command(..., rule=to_me(), ...)`构建的事件响应器无法被带有at机器人的命令消息触发  
我同时尝试使用用`@bot /cmd arg`和`@bot cmd arg`的形式发送指令，都无法触发

### 复现步骤

参见截图中的实例

### 截图或日志

1. 带有`rule=to_me()`的事件响应器和处理函数：
![image](https://github.com/nonebot/adapter-satori/assets/38141753/de6d548a-0394-40fc-be03-8734066021a6)
![image](https://github.com/nonebot/adapter-satori/assets/38141753/f28c3d99-39eb-4dc7-9fee-5cf28873fe36)
2. 尝试触发命令，失败（中间是打印的`event.message.content)`：
<img width="1739" alt="image" src="https://github.com/nonebot/adapter-satori/assets/38141753/94354b33-e04b-449a-a431-c726c1d691cb">
3. 不带`rule=to_me()`的事件响应器和处理函数：
![image](https://github.com/nonebot/adapter-satori/assets/38141753/ff79aa5e-9941-420b-9818-ef2dfff00c89)
![image](https://github.com/nonebot/adapter-satori/assets/38141753/60ff1e37-717f-42cd-ae76-81d78456ec67)
4. 尝试触发命令，成功：
<img width="1652" alt="image" src="https://github.com/nonebot/adapter-satori/assets/38141753/1f2ce5b7-20d5-46d1-ab00-a3153be93f6a">

**Comment by RF-Tar-Railt** [comment]
at bot的消息长啥样

**Comment by LiXDL** [comment]
QQ里面是这样的：
![image](https://github.com/nonebot/adapter-satori/assets/38141753/47e9b4dc-cf9e-4ad5-8283-a25bca354197)

Chronocat日志里面是这样的：
<img width="513" alt="image" src="https://github.com/nonebot/adapter-satori/assets/38141753/19ca5ec7-06bf-49f2-bce7-39aeb209d5ff">

**Comment by RF-Tar-Railt** [comment]
我是说nb收到的，那个日志里面是怎么显示的

**Comment by LiXDL** [comment]
<img width="1733" alt="image" src="https://github.com/nonebot/adapter-satori/assets/38141753/55066df6-270f-4a9f-aad1-c9e64a96cf5a">
↑这个样子的，nb里面好像没法看到被at的用户。

**Comment by LiXDL** [comment]
<img width="1656" alt="image" src="https://github.com/nonebot/adapter-satori/assets/38141753/1d7903ab-4663-411e-8f50-5324c925fc7f">
又试了试，NB日志里也没法直接看到回复消息，如果带了at也会阻止触发本来可用的命令。

**Comment by RF-Tar-Railt** [comment]
消息事件有一个original_message，你同时把get_message()的内容和original_message的内容打印一下看看
同时测试一下at bot和at他人

**Comment by LiXDL** [comment]
![image](https://github.com/nonebot/adapter-satori/assets/38141753/0f58e97f-7a82-4630-b2d6-ff577513d0a3)
![image](https://github.com/nonebot/adapter-satori/assets/38141753/86ce8ca1-cb6c-42d7-a85d-43aaa2e5f0e9)
↑如图所示

log level设定到trace会提示Rule conditions not met for Matcher，对应上面构造的那个带有rule=to_me的事件响应器。

**Comment by RF-Tar-Railt** [comment]
> ![image](https://private-user-images.githubusercontent.com/38141753/324874542-0f58e97f-7a82-4630-b2d6-ff577513d0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODM1MzAsIm5iZiI6MTcxMzg4MzIzMCwicGF0aCI6Ii8zODE0MTc1My8zMjQ4NzQ1NDItMGY1OGU5N2YtN2E4Mi00NjMwLWIyZDYtZmY1Nzc1MTNkMGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE0NDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZTdhMTU3YjVhYjA1N2QyMjEyZDMxMzY0YmU0NDNmNTRmMzc5OWQwM2I2MTgxYThmYWIzYzM5ZjFlMWU0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Od7NoXdqKj5eSYYS6Ta3EnXp8a1gd0o8feTlPG133ww) ![image](https://private-user-images.githubusercontent.com/38141753/324874617-86ce8ca1-cb6c-42d7-a85d-43aaa2e5f0e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODM1MzAsIm5iZiI6MTcxMzg4MzIzMCwicGF0aCI6Ii8zODE0MTc1My8zMjQ4NzQ2MTctODZjZThjYTEtY2I2Yy00MmQ3LWE4NWQtNDNhYWEyZTVmMGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE0NDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YjE0MzhjYmM5ZDEyNWIxNDQwZjQ0YWI2NzU0ZjU2MTlkMzM3ZGIyMjMxODkwYjAwMDVkMWNhM2M4NDA4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZxVqkSrSIxhN7Sxi6C1FsC6wd3qyL79iO-2ve9oOzi0) ↑如图所示
> 
> log level设定到trace会提示Rule conditions not met for Matcher，对应上面构造的那个带有rule=to_me的事件响应器。

你是at的bot吗，你打印一下bot的self_id看看

**Comment by LiXDL** [comment]
![image](https://github.com/nonebot/adapter-satori/assets/38141753/25f59b1f-36a0-48bb-9b73-6511e533dd81)
是的哇，我这个测试群里只有我自己的号和这个bot了😭

**Comment by RF-Tar-Railt** [comment]
你把消息事件数据发一下，转成dict（用event.dict())

**Comment by LiXDL** [comment]
如下
```
{'argv': None,
 'button': None,
 'channel': {'id': 测试群号,
             'name': 'Backup',
             'parent_id': None,
             'type': <ChannelType.TEXT: 0>},
 'guild': {'avatar': 'https://p.qlogo.cn/gh/测试群号/测试群号/640',
           'id': 测试群号,
           'name': 'Backup'},
 'id': 54,
 'login': None,
 'member': {'avatar': None,
            'joined_at': None,
            'name': None,
            'nick': None,
            'user': None},
 'message': {'channel': None,
             'content': '<at id="3668701134" name="神秘虾头男"/> repeat_raw 打印dict',
             'created_at': None,
             'guild': None,
             'id': '7361076614359645153',
             'member': None,
             'updated_at': None,
             'user': None},
 'operator': None,
 'original_message': [{'data': {'id': '3668701134', 'name': '神秘虾头男'},
                       'type': 'at'},
                      {'data': {'styles': {}, 'text': ' repeat_raw 打印dict'},
                       'type': 'text'}],
 'platform': 'chronocat',
 'reply': None,
 'role': None,
 'self_id': '3668701134',
 'timestamp': datetime.datetime(2024, 4, 23, 22, 56, 46),
 'to_me': True,
 'type': 'message-created',
 'user': {'avatar': 'http://thirdqq.qlogo.cn/headimg_dl?dst_uin=我的QQ号&spec=640',
          'id': 我的QQ号,
          'is_bot': None,
          'name': '潇洒',
          'nick': None}}
```

**Comment by RF-Tar-Railt** [comment]
> 如下
> 
> ```
> {'argv': None,
>  'button': None,
>  'channel': {'id': 测试群号,
>              'name': 'Backup',
>              'parent_id': None,
>              'type': <ChannelType.TEXT: 0>},
>  'guild': {'avatar': 'https://p.qlogo.cn/gh/测试群号/测试群号/640',
>            'id': 测试群号,
>            'name': 'Backup'},
>  'id': 54,
>  'login': None,
>  'member': {'avatar': None,
>             'joined_at': None,
>             'name': None,
>             'nick': None,
>             'user': None},
>  'message': {'channel': None,
>              'content': '<at id="3668701134" name="神秘虾头男"/> repeat_raw 打印dict',
>              'created_at': None,
>              'guild': None,
>              'id': '7361076614359645153',
>              'member': None,
>              'updated_at': None,
>              'user': None},
>  'operator': None,
>  'original_message': [{'data': {'id': '3668701134', 'name': '神秘虾头男'},
>                        'type': 'at'},
>                       {'data': {'styles': {}, 'text': ' repeat_raw 打印dict'},
>                        'type': 'text'}],
>  'platform': 'chronocat',
>  'reply': None,
>  'role': None,
>  'self_id': '3668701134',
>  'timestamp': datetime.datetime(2024, 4, 23, 22, 56, 46),
>  'to_me': True,
>  'type': 'message-created',
>  'user': {'avatar': 'http://thirdqq.qlogo.cn/headimg_dl?dst_uin=我的QQ号&spec=640',
>           'id': 我的QQ号,
>           'is_bot': None,
>           'name': '潇洒',
>           'nick': None}}
> ```

?你这tome已经是True了啊

**Comment by LiXDL** [comment]
但是并不会触发带有`rule=to_me()`的响应器，就是我最开始那个截图里面定义的repeat_raw；包括没有指定rule的普通响应器也没有办法通过`@bot /cmd arg`这种形式触发。
莫非satori adapter设计的就是这样吗。

**Comment by LiXDL** [comment]
明天下班了我再测测

**Comment by RF-Tar-Railt** [comment]
我这边to_me是正常的

**Comment by LiXDL** [comment]
太奇怪了，所有部分的`event.is_tome()`evaluate出来都是true，但是就是无法通过rule checker。
我看nb官方实例是允许`/cmd`和`@bot cmd`这种调用方法的，在第一种我能用的情况下第二种就是用不了。

**Comment by RF-Tar-Railt** [comment]
> 太奇怪了，所有部分的`event.is_tome()`evaluate出来都是true，但是就是无法通过rule checker。
> 我看nb官方实例是允许`/cmd`和`@bot cmd`这种调用方法的，在第一种我能用的情况下第二种就是用不了。

你不应该是@bot /cmd吗

**Comment by LiXDL** [comment]
> > 太奇怪了，所有部分的`event.is_tome()`evaluate出来都是true，但是就是无法通过rule checker。
> > 我看nb官方实例是允许`/cmd`和`@bot cmd`这种调用方法的，在第一种我能用的情况下第二种就是用不了。
> 
> 你不应该是@bot /cmd吗

![64467e3f6a2e0f2cbb425ce30e938f07_720](https://github.com/nonebot/adapter-satori/assets/38141753/260bf0b4-76dc-4c34-876f-ebbed737ac03)
但是也不行。

**Comment by RF-Tar-Railt** [comment]
> > > 太奇怪了，所有部分的`event.is_tome()`evaluate出来都是true，但是就是无法通过rule checker。
> > > 我看nb官方实例是允许`/cmd`和`@bot cmd`这种调用方法的，在第一种我能用的情况下第二种就是用不了。
> > 
> > 你不应该是@bot /cmd吗
> 
> ![64467e3f6a2e0f2cbb425ce30e938f07_720](https://github.com/nonebot/adapter-satori/assets/38141753/260bf0b4-76dc-4c34-876f-ebbed737ac03)
> 但是也不行。

你能debug吗，调试进tome的rule里看看

**Comment by LiXDL** [comment]
![image](https://github.com/nonebot/adapter-satori/assets/38141753/12742242-dc9c-41e5-ae13-eeea8342b346)
![image](https://github.com/nonebot/adapter-satori/assets/38141753/7780745f-43a1-4f41-9f9a-03aac7931587)
我之前在nb的源码这里放print测试了一下，确实拿到的就是satori的MessageEvent object，然后也调用的`is_tome()`这个函数，结果为True。

**Comment by RF-Tar-Railt** [comment]
> ![image](https://github.com/nonebot/adapter-satori/assets/38141753/12742242-dc9c-41e5-ae13-eeea8342b346)
> ![image](https://github.com/nonebot/adapter-satori/assets/38141753/7780745f-43a1-4f41-9f9a-03aac7931587)
> 我之前在nb的源码这里放print测试了一下，确实拿到的就是satori的MessageEvent object，然后也调用的`is_tome()`这个函数，结果为True。

event.get_message()得到的消息带了at吗

**Comment by LiXDL** [comment]
带了：
![image](https://github.com/nonebot/adapter-satori/assets/38141753/fe70fe89-d231-4884-a3ee-4aeffae13784)
![image](https://github.com/nonebot/adapter-satori/assets/38141753/83b9cf84-21fd-4e54-a1d7-128a3b125274)

**Comment by RF-Tar-Railt** [comment]
> 带了：
> ![image](https://github.com/nonebot/adapter-satori/assets/38141753/fe70fe89-d231-4884-a3ee-4aeffae13784)
> ![image](https://github.com/nonebot/adapter-satori/assets/38141753/83b9cf84-21fd-4e54-a1d7-128a3b125274)
> 

那就是这个问题了，at bot自己的话这个at应该要被去掉的

你去bot.py文件那里有个check_at_me，你调试一下看看

**Comment by LiXDL** [comment]
> > 带了：
> > ![image](https://private-user-images.githubusercontent.com/38141753/325275256-fe70fe89-d231-4884-a3ee-4aeffae13784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzE3OTksIm5iZiI6MTcxMzk3MTQ5OSwicGF0aCI6Ii8zODE0MTc1My8zMjUyNzUyNTYtZmU3MGZlODktZDIzMS00ODg0LWEzZWUtNGFlZmZhZTEzNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE1MTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZmJmYWJiMTliYTNlNjVmMTZlM2QxNGIxODBmYTIzYmY3ZGFjODNkMjQ3MmEyMzUxMDkxNzhkMTBkODU5ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yg-3jTHgAdvd9s_Esxf-9iY2X72RfsUVwXEpTY6wWOQ)
> > ![image](https://private-user-images.githubusercontent.com/38141753/325275319-83b9cf84-21fd-4e54-a1d7-128a3b125274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzE3OTksIm5iZiI6MTcxMzk3MTQ5OSwicGF0aCI6Ii8zODE0MTc1My8zMjUyNzUzMTktODNiOWNmODQtMjFmZC00ZTU0LWExZDctMTI4YTNiMTI1Mjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE1MTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjNmOTg5N2RmNDNlM2E1ZjkwMjExNThkMjc5OWY0NjdlNWRmNzQ3ODgyMmI4M2M4OTNlYTI2YzU5ZTlkOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xd8AvW7UCpeQ-Uk5vx1VrU1GjviTYHg2EyGMcrozXHY)
> 
> 那就是这个问题了，at bot自己的话这个at应该要被去掉的
> 
> 你去bot.py文件那里有个check_at_me，你调试一下看看

是satori adapter里的bot.py对_check_at_me的实现部分吗？

**Comment by RF-Tar-Railt** [comment]
> > > 带了：
> > > ![image](https://private-user-images.githubusercontent.com/38141753/325275256-fe70fe89-d231-4884-a3ee-4aeffae13784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzE3OTksIm5iZiI6MTcxMzk3MTQ5OSwicGF0aCI6Ii8zODE0MTc1My8zMjUyNzUyNTYtZmU3MGZlODktZDIzMS00ODg0LWEzZWUtNGFlZmZhZTEzNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE1MTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZmJmYWJiMTliYTNlNjVmMTZlM2QxNGIxODBmYTIzYmY3ZGFjODNkMjQ3MmEyMzUxMDkxNzhkMTBkODU5ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yg-3jTHgAdvd9s_Esxf-9iY2X72RfsUVwXEpTY6wWOQ)
> > > ![image](https://private-user-images.githubusercontent.com/38141753/325275319-83b9cf84-21fd-4e54-a1d7-128a3b125274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzE3OTksIm5iZiI6MTcxMzk3MTQ5OSwicGF0aCI6Ii8zODE0MTc1My8zMjUyNzUzMTktODNiOWNmODQtMjFmZC00ZTU0LWExZDctMTI4YTNiMTI1Mjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE1MTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjNmOTg5N2RmNDNlM2E1ZjkwMjExNThkMjc5OWY0NjdlNWRmNzQ3ODgyMmI4M2M4OTNlYTI2YzU5ZTlkOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xd8AvW7UCpeQ-Uk5vx1VrU1GjviTYHg2EyGMcrozXHY)
> > 
> > 
> > 那就是这个问题了，at bot自己的话这个at应该要被去掉的
> > 你去bot.py文件那里有个check_at_me，你调试一下看看
> 
> 是satori adapter里的bot.py对_check_at_me的实现部分吗？

对
记得print(repr(message))

**Comment by LiXDL** [comment]
![image](https://github.com/nonebot/adapter-satori/assets/38141753/11fbb816-83cc-4c69-bc25-33d5e09ea5d7)

奇怪，看起来这部分调用确实是把前面的at移除了，但是进到我的自定义hook和最终插件里的时候又回来了

**Comment by RF-Tar-Railt** [comment]
你hook怎么整的

**Comment by LiXDL** [comment]
> 你hook怎么整的

就是用来忽略bot自己发出去的消息，避免触发响应器（本来是预留给在部分群禁用bot的功能的
```
@event_preprocessor
async def silence_preprocessor(bot: SatoriBot, event: SatoriMessageEvent):
    if event.user.id == bot.self_id:
        raise IgnoredException("Self message. Ignored.")
    #   Only effective for group messages
    if event.guild is None:
        return

    group_id = event.guild.id

    logger.critical(f"In event_preprocessor: {repr(event.get_message())}")
    # pprint.pprint(event.dict())
    # print(event.is_tome())
```

**Comment by RF-Tar-Railt** [comment]
好，我这边复现了

**Comment by LiXDL** [comment]
太强了大哥！
我明天上班，晚上再来继续努力。

**Comment by RF-Tar-Railt** [comment]
> 太强了大哥！ 我明天上班，晚上再来继续努力。

临时解决方案，`async def silence_preprocessor(bot: SatoriBot, event):`

把event的类型去掉就没有出现这个问题
