### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CaviarSP** [nonebot/adapter-satori#19]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个 Bug
- [ ] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.12.3

### NoneBot 版本

2.2.1

### 适配器

0.10.5

### 协议端

Chronocat/0.2.9

### 描述问题

```
url1 = https://i.pixiv.cat/user-profile/img/2019/06/08/18/15/46/15864250_3a16ed5563079c651f041ee27950de74_170.png
url2 = https://tse2-mm.cn.bing.net/th/id/OIP-C.zRGpb4aW12GQGH5L3_sz-wHaHa?rs=1&pid=ImgDetMain
```
在`send_message`发送图片信息时，url1请求失败（超时），url2正常发送。在不开代理的情况下，两个url都能正常访问（包括浏览器和requests）。

### 复现步骤

1.对上述url用`Messagesegment`类下的`Image.image`构建图片信息；
2.用`matcher.send`或`bot.send_message`发送图片信息；
3.url2 的消息正常发送，url1的信息报错如下：
图1为nonebot的log
![1](https://github.com/nonebot/adapter-satori/assets/147965612/db6688d3-dc66-4ead-b42e-4bf456962e3c)
图2为chronocat的log
![2](https://github.com/nonebot/adapter-satori/assets/147965612/1a844c1a-ba92-4d11-92b3-01ae7ab353b8)

**Comment by RF-Tar-Railt** [comment]
这个问题你应该去问 chronocat，nb这边用url发图片是直接把链接给cc的，nb没有处理
