### ISSUE TITLE
[Feature] 需要MessageEvent携带消息发送者在群内的role

### ISSUE THREAD

**Issue by Polyisoprene** [nonebot/adapter-satori#2]
## 请确认：

* [x] 新特性的目的明确
* [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并且找不到类似特性

### 概要

MessageEvent 如果是群消息，则携带发送消息者在群组内的身份，如群员、群主、管理员

### 是否已有相关实现

onebot的GroupMessageEvent的event.sender.role

**Comment by RF-Tar-Railt** [comment]
首先，这里是适配器，没有办法管到协议本身的特性需求
其次，satori 已经存在 `event.role` 属性，若为空值，那是你连接的协议实现端自己没有实现这个属性，你应该去你连接的协议实现端的仓库提出你的需求
