### ISSUE TITLE
[Feature] 支持QQNT的Markdown语法

### ISSUE THREAD

**Issue by iceriny** [nonebot/adapter-satori#20]
## 请确认：
* [x] 新特性的目的明确
* [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并且找不到类似特性

### 概要
支持QQNT的Markdown语法

### 是否已有相关实现
暂无

### 其他内容
暂无

**Comment by RF-Tar-Railt** [comment]
首先，markdown不是 satori 标准下的元素
其次，对于 chronocat，你可以直接构造 MessageSegment("chronocat:markdown", {"content": xxx}) 去发送

**Comment by iceriny** [comment]
> 直接构造 MessageSegment("chronocat:markdown", {"content": xxx}) 去发送
我尝试了下但是给出了错误:
```
nonebot.adapters.satori.exception.ApiNotImplementedException: <ApiNotImplementedException: 500, headers=<CIMultiDict('Server': 'Chronocat/0.2.9', 'X-Powered-By': 'Chronocat/0.2.9', 'Date': 'Wed, 01 May 2024 05:14:03 GMT', 'Connection': 'keep-alive', 'Keep-Alive': 'timeout=5', 'Transfer-Encoding': 'chunked')>, content=b'500 internal server error\nError: \xe6\xb2\xa1\xe6\x9c\x89\xe5\xbc\x95\xe6\x93\x8e\xe6\x8f\x90\xe4\xbe\x9b \x1b[35mchronocat.internal.message.create2.markdown\x1b[39m\xe3\x80\x82\xe5\x8f\xaf\xe8\x83\xbd\xe6\xb2\xa1\xe6\x9c\x89\xe5\x8a\xa0\xe8\xbd\xbd\xe6\x89\x80\xe9\x9c\x80\xe7\x9a\x84\xe5\xbc\x95\xe6\x93\x8e\xef\xbc\x9f'>
```
抱歉，我只是个业余的 >.<

**Comment by RF-Tar-Railt** [comment]
> > 直接构造 MessageSegment("chronocat:markdown", {"content": xxx}) 去发送
> 我尝试了下但是给出了错误:
> ```
> nonebot.adapters.satori.exception.ApiNotImplementedException: <ApiNotImplementedException: 500, headers=<CIMultiDict('Server': 'Chronocat/0.2.9', 'X-Powered-By': 'Chronocat/0.2.9', 'Date': 'Wed, 01 May 2024 05:14:03 GMT', 'Connection': 'keep-alive', 'Keep-Alive': 'timeout=5', 'Transfer-Encoding': 'chunked')>, content=b'500 internal server error\nError: \xe6\xb2\xa1\xe6\x9c\x89\xe5\xbc\x95\xe6\x93\x8e\xe6\x8f\x90\xe4\xbe\x9b \x1b[35mchronocat.internal.message.create2.markdown\x1b[39m\xe3\x80\x82\xe5\x8f\xaf\xe8\x83\xbd\xe6\xb2\xa1\xe6\x9c\x89\xe5\x8a\xa0\xe8\xbd\xbd\xe6\x89\x80\xe9\x9c\x80\xe7\x9a\x84\xe5\xbc\x95\xe6\x93\x8e\xef\xbc\x9f'>
> ```
> 抱歉，我只是个业余的 >.< 
> 

抱歉，cc那边发md应该是MessageSegment("chronocat:markdown")(
    "md文本"
)

其次你确认一下cc现在是否还能发送md消息（tx更新过了）

**Comment by iceriny** [comment]
> > > 直接构造 MessageSegment("chronocat:markdown", {"content": xxx}) 去发送 
> > > 我尝试了下但是给出了错误:
> > 
> > 
> > ```
> > nonebot.adapters.satori.exception.ApiNotImplementedException: <ApiNotImplementedException: 500, headers=<CIMultiDict('Server': 'Chronocat/0.2.9', 'X-Powered-By': 'Chronocat/0.2.9', 'Date': 'Wed, 01 May 2024 05:14:03 GMT', 'Connection': 'keep-alive', 'Keep-Alive': 'timeout=5', 'Transfer-Encoding': 'chunked')>, content=b'500 internal server error\nError: \xe6\xb2\xa1\xe6\x9c\x89\xe5\xbc\x95\xe6\x93\x8e\xe6\x8f\x90\xe4\xbe\x9b \x1b[35mchronocat.internal.message.create2.markdown\x1b[39m\xe3\x80\x82\xe5\x8f\xaf\xe8\x83\xbd\xe6\xb2\xa1\xe6\x9c\x89\xe5\x8a\xa0\xe8\xbd\xbd\xe6\x89\x80\xe9\x9c\x80\xe7\x9a\x84\xe5\xbc\x95\xe6\x93\x8e\xef\xbc\x9f'>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 抱歉，我只是个业余的 >.<
> 
> 抱歉，cc那边发md应该是MessageSegment("chronocat:markdown")( "md文本" )
> 
> 其次你确认一下cc现在是否还能发送md消息（tx更新过了）

好哦，我试试，感谢!
