### ISSUE TITLE
[Bug]: 使用Satori适配器连接QQ的时候，发送消息会连续发送两条

### ISSUE THREAD

**Issue by fataldemon** [nonebot/adapter-satori#27]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个 Bug
- [ ] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.10

### NoneBot 版本

2.3.2

### 适配器

0.12.3

### 协议端

chronocat

### 描述问题

之前我是按照red的适配器来使用的，但是pydantic升级到最新版以后red就会报错。我看到Satori适配器可以接收到QQ的消息，于是进行了迁移，但是遇到两个问题：
1、在用on_command()发送回复的时候，我对MessageEvent进行响应，消息可以发出来，但是每次总是会发出两条消息；
2、MessageSegment的使用方式，我用MessageSegment.image()好像没法发送图片出来。不知道是不是我路径的格式不对？

### 复现步骤

![image](https://github.com/user-attachments/assets/9d3049be-7d8d-450b-9ca4-7e2104fab21c)
![image](https://github.com/user-attachments/assets/d9b534b6-a9af-4fc2-95f2-fb64fd294633)
![image](https://github.com/user-attachments/assets/34ef457e-3a45-41dd-a8d7-0c937c149189)

**Comment by fataldemon** [comment]
第一个问题是我傻逼了=。= 请大佬无视

**Comment by RF-Tar-Railt** [comment]
```python
    @staticmethod
    def image(
        url: Optional[str] = None,
        path: Optional[Union[str, Path]] = None,
        raw: Optional[Union[bytes, BytesIO]] = None,
        mime: Optional[str] = None,
        name: Optional[str] = None,
        extra: Optional[dict] = None,
        cache: Optional[bool] = None,
        timeout: Optional[int] = None,
    ) -> "Image":
```

你想用本地文件发图的话应该用image(path=...)

**Comment by fataldemon** [comment]
> ```python
>     @staticmethod
>     def image(
>         url: Optional[str] = None,
>         path: Optional[Union[str, Path]] = None,
>         raw: Optional[Union[bytes, BytesIO]] = None,
>         mime: Optional[str] = None,
>         name: Optional[str] = None,
>         extra: Optional[dict] = None,
>         cache: Optional[bool] = None,
>         timeout: Optional[int] = None,
>     ) -> "Image":
> ```
> 
> 你想用本地文件发图的话应该用image(path=...)

![image](https://github.com/user-attachments/assets/70fdac83-fce1-422a-95c3-801ee85e74c3)
我试了下，但是好像还是发不出来的样子。。明明这样打印出来的路径是对的
![image](https://github.com/user-attachments/assets/02f806ce-53a5-47d5-a28c-d0fb8c413591)
![image](https://github.com/user-attachments/assets/b9e82f83-4cf5-43e9-b915-2d26a45fd073)

**Comment by RF-Tar-Railt** [comment]
chronocat那边的日志呢

**Comment by fataldemon** [comment]
chronocat的日志在哪里找，是在.chronocat文件夹下吗

**Comment by RF-Tar-Railt** [comment]
> chronocat的日志在哪里找，是在.chronocat文件夹下吗

cc不是启动后有控制台的吗

**Comment by fataldemon** [comment]
我懂了 可能是我的chronocat版本太旧了

**Comment by fataldemon** [comment]
谢谢大佬，问题已解决！
