### ISSUE TITLE
使用Chronocat+satori时如何关闭自身上报功能？

### ISSUE THREAD

**Issue by vllbc** [nonebot/adapter-satori#33]
如何实现将机器人的发言不上报，即机器人的发言无法触发指令，否则如果设置`COMMAND_START=["", "/"]`，会有陷入死循环的风险，机器人不断触发自己的发言对应的指令，只能通过结束机器人来解决，请问该如何关闭自身上报功能？

**Comment by RF-Tar-Railt** [comment]
这个你应该找chronocat询问是否能配置关闭上报自身消息
