### ISSUE TITLE
[Bug] Bot接收群组成员增加事件时程序报错

### ISSUE THREAD

**Issue by reine-ishyanami** [nonebot/adapter-satori#4]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个Bug

# Bug

## 问题
Bot接收群组成员增加事件时程序报错

## 如何复现
在群聊中邀请Bot账号加入群聊，事件响应器注入`GuildInnerMemberAddedEvent`事件（即Bot加入新群聊产生的事件）无法被正常解析 

## 预期行为
事件响应器正常解析`GuildInnerMemberAddedEvent`事件

## 使用环境:
- 操作系统 (Windows/Linux/Mac): Windows
- Python 版本: python3.10
- Nonebot2 版本: 2.1.1
- 适配器版本: 0.6.1
- 使用的 Satori 服务端 (例如 Chronocat): Chronocat

## 日志/截图
![image](https://github.com/nonebot/adapter-satori/assets/46278371/66305349-4f04-4819-a62b-345705aad931)

![image](https://github.com/nonebot/adapter-satori/assets/46278371/eee10c17-b97f-4142-bc95-e8795659caca)

**尝试将代码中 `event.py` 中的第135行注释可正常使用事件响应器**

**Comment by RF-Tar-Railt** [comment]
按理说这个属于chronocat那边的bug，不过我这边改改吧

**Comment by RF-Tar-Railt** [comment]
事件名应该是 `GuildMemberAddedEvent` 才对（
