### ISSUE TITLE
[Bug] 发送本地绝对路径格式的图片无返回值

### ISSUE THREAD

**Issue by contr4l** [nonebot/adapter-satori#7]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个Bug

# Bug

## 问题
发送图片接口中，将url指定为file:///格式的本地绝对路径，create_message无返回值

## 如何复现
后端为adapter-satori, 协议端为chronocat 0.52，仅本地路径形式的图片发送存在问题

## 预期行为
可以使用绝对路径发送，例如：{'type': 'img', 'data': {'src': 'file:///C:\\Users\\Public\\gocqhttp\\data\\images\\817815373\\a75d121be086f93df202810d311b70df.gif'}}

## 使用环境:
- 操作系统 (Windows/Linux/Mac): Windows 11
- Python 版本: python3.11
- Nonebot2 版本: 2.1.1
- 适配器版本: 0.8.1
- 使用的 Satori 服务端 (例如 Chronocat): Chronocat 0.52

## 日志/截图
12-13 16:59:48 [INFO] nonebot | Matcher(type='message', module=iCore.bot.interpreter, lineno=171) running complete
{'type': 'img', 'data': {'src': 'file:///C:\\Users\\Public\\gocqhttp\\data\\images\\817815373\\a75d121be086f93df202810d311b70df.gif'}}
request is: Request(method='POST', url='http://localhost:5500/v1/message.create')
content is <img src="file:///C:\Users\Public\gocqhttp\data\images\817815373\a75d121be086f93df202810d311b70df.gif"/>
12-13 16:59:49 [WARNING] apscheduler | Execution of job "none_bot_work_queue (trigger: interval[0:00:01], next run at: 2023-12-13 16:59:49 CST)" skipped: maximum number of running instances reached (1)
12-13 16:59:50 [WARNING] apscheduler | Execution of job "none_bot_work_queue (trigger: interval[0:00:01], next run at: 2023-12-13 16:59:50 CST)" skipped: maximum number of running instances reached (1)
12-13 16:59:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=iCore.bot.interpreter, lineno=171)
12-13 16:59:51 [INFO] nonebot | Matcher(type='message', module=iCore.bot.interpreter, lineno=171) running complete
res is []
![image](https://github.com/nonebot/adapter-satori/assets/30452426/a8a7eb3d-4901-442f-9e72-a1ccf42a80ae)

**Comment by contr4l** [comment]
问题更新：尝试使用raw字段时，在create_message这一步，content变成空值。

**Comment by RF-Tar-Railt** [comment]
> 问题更新：尝试使用raw字段时，在create_message这一步，content变成空值。

这个应该是你没传对参数

**Comment by RF-Tar-Railt** [comment]
然后的话，发图失败应该是chronocat那边的问题

**Comment by contr4l** [comment]
> > 问题更新：尝试使用raw字段时，在create_message这一步，content变成空值。
> 
> 这个应该是你没传对参数

从添加的打印结果来看，base64的编码结果是对的，但问题我先关掉了，satori协议还是有诸多不太好用的地方。
